---
# - hosts: all
#   become: yes
#   vars_files:
#     - vars/all.yml 
#   roles:
#     - commons

- hosts: masters
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - { role: master, tags: master }
    - { role: cni, tags: cni }

- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


# - hosts: workers
#   become: yes
#   tasks:
#     - name: join cluster
#       shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
#       args:
#         chdir: $HOME
#         creates: node_joined.txt

- hosts: workers
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - { role: worker, tags: workers } 

- hosts: masters
  become: yes
  vars_files:
    - vars/all.yml
  gather_facts: yes 
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck