---
cluster:
    install: '1'
    packages: [vim, git, htop,zip, unzip, apt-transport-https, ca-certificates, curl, wget, gnupg2, software-properties-common,net-tools, ntpdate, git-core, jq]
    workes: [python3-pip, virtualenv, python3-setuptools, docker-ce, net-tools, ntpdate, bridge-utils]
    masters: [bridge-utils]
    timezone: America/Sao_Paulo
    locale: pt_BR.UTF-8
    domain: dtux.lan
    users: [ ubuntu ]
 
CLUSETER_IP: 10.32.0.0/24

APISERVER_SERVICE_IP: 10.32.0.1

# Certificates directory
PKI_DIR: '{{ playbook_dir }}/certificates'

# Kubeconfig directory
CONF_DIR: '{{ playbook_dir }}/kubeconfig'

# Binaries directory
BIN_DIR: '{{ playbook_dir }}/bin'