---
# Run a docker image to visualize the cluster

- name: Check if the visualization container is running
  command: docker ps
  register: docker_ps
  changed_when: false
 

- name: Start visualization container
  command: docker service create  --name=visualizer --publish=8080:8080/tcp --constraint=node.role==manager --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock  dockersamples/visualizer:latest
  when: "docker_ps.stdout.find('visualizer') == -1"